---

name: Build documents
'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: bergentroll/pali-english-recitations-builder:latest
    permissions:
      contents: write
    steps:
      - uses: sasanarakkha/document-build-actions@v1
        with:
          build_epub: false
          validate_epub: false